//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tecsshcop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEC_CLIENTES
    {
        public int COD_CLIENTE { get; set; }
        public Nullable<int> COD_PEDIDO { get; set; }
        public string DSC_CLIENTE { get; set; }
        public string DSC_EMAIL { get; set; }
        public Nullable<System.DateTime> DTA_NASCIMENTO { get; set; }
        public string DSC_GENERO { get; set; }
        public string DSC_NUMERO_VAT { get; set; }
        public string DSC_TELEFONE1 { get; set; }
        public string DSC_TELEFONE2 { get; set; }
        public string DSC_TELEFONE3 { get; set; }
        public string DSC_TELEFONE4 { get; set; }
    
        public virtual TEC_PEDIDOS TEC_PEDIDOS { get; set; }
        public virtual TEC_PEDIDOS TEC_PEDIDOS1 { get; set; }
        public virtual TEC_PEDIDOS TEC_PEDIDOS2 { get; set; }
        public virtual TEC_PEDIDOS TEC_PEDIDOS3 { get; set; }
        public virtual TEC_PEDIDOS TEC_PEDIDOS4 { get; set; }
    }
}
