//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tecsshcop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEC_PEDIDOS
    {
        public TEC_PEDIDOS()
        {
            this.TEC_CLIENTES = new HashSet<TEC_CLIENTES>();
            this.TEC_CLIENTES1 = new HashSet<TEC_CLIENTES>();
            this.TEC_CLIENTES2 = new HashSet<TEC_CLIENTES>();
            this.TEC_CLIENTES3 = new HashSet<TEC_CLIENTES>();
            this.TEC_CLIENTES4 = new HashSet<TEC_CLIENTES>();
            this.TEC_ENDERECO = new HashSet<TEC_ENDERECO>();
            this.TEC_ENDERECO1 = new HashSet<TEC_ENDERECO>();
            this.TEC_ENDERECO2 = new HashSet<TEC_ENDERECO>();
            this.TEC_ENDERECO3 = new HashSet<TEC_ENDERECO>();
            this.TEC_ENDERECO4 = new HashSet<TEC_ENDERECO>();
            this.TEC_ENDERECO5 = new HashSet<TEC_ENDERECO>();
            this.TEC_FATURA = new HashSet<TEC_FATURA>();
            this.TEC_FATURA1 = new HashSet<TEC_FATURA>();
            this.TEC_FATURA2 = new HashSet<TEC_FATURA>();
            this.TEC_FATURA3 = new HashSet<TEC_FATURA>();
            this.TEC_FATURA4 = new HashSet<TEC_FATURA>();
            this.TEC_ITEM_PEDIDO = new HashSet<TEC_ITEM_PEDIDO>();
            this.TEC_PAGAMENTO = new HashSet<TEC_PAGAMENTO>();
            this.TEC_PAGAMENTO1 = new HashSet<TEC_PAGAMENTO>();
            this.TEC_PAGAMENTO2 = new HashSet<TEC_PAGAMENTO>();
            this.TEC_PAGAMENTO3 = new HashSet<TEC_PAGAMENTO>();
            this.TEC_PAGAMENTO4 = new HashSet<TEC_PAGAMENTO>();
        }
    
        public int COD_PEDIDO { get; set; }
        public string DSC_CANAL { get; set; }
        public string COD_CANAL { get; set; }
        public Nullable<System.DateTime> DTA_ESTIMADA_ENTREGA { get; set; }
        public Nullable<decimal> DSC_INTERECE { get; set; }
        public Nullable<System.DateTime> DTA_LOCALIZADO_DESDE { get; set; }
        public string DSC_STATUS_SINCRONIZACAO { get; set; }
        public Nullable<decimal> DSC_VALOR_COMPRA { get; set; }
        public string DSC_METODO_COMPR { get; set; }
        public Nullable<System.DateTime> DTA_ATUALIZACAO { get; set; }
        public Nullable<decimal> DSC_TOTAL_PEDIDO { get; set; }
        public Nullable<decimal> DSC_CUSTO_ENTREGA { get; set; }
        public string DSC_METODO_ENTREGA { get; set; }
        public Nullable<int> IND_IMPORTADO { get; set; }
        public Nullable<int> COD_VENDEDOR { get; set; }
        public Nullable<int> IND_ATIVO { get; set; }
        public Nullable<System.DateTime> DTA_SINCRONIZACAO { get; set; }
    
        public virtual ICollection<TEC_CLIENTES> TEC_CLIENTES { get; set; }
        public virtual ICollection<TEC_CLIENTES> TEC_CLIENTES1 { get; set; }
        public virtual ICollection<TEC_CLIENTES> TEC_CLIENTES2 { get; set; }
        public virtual ICollection<TEC_CLIENTES> TEC_CLIENTES3 { get; set; }
        public virtual ICollection<TEC_CLIENTES> TEC_CLIENTES4 { get; set; }
        public virtual ICollection<TEC_ENDERECO> TEC_ENDERECO { get; set; }
        public virtual ICollection<TEC_ENDERECO> TEC_ENDERECO1 { get; set; }
        public virtual ICollection<TEC_ENDERECO> TEC_ENDERECO2 { get; set; }
        public virtual ICollection<TEC_ENDERECO> TEC_ENDERECO3 { get; set; }
        public virtual ICollection<TEC_ENDERECO> TEC_ENDERECO4 { get; set; }
        public virtual ICollection<TEC_ENDERECO> TEC_ENDERECO5 { get; set; }
        public virtual ICollection<TEC_FATURA> TEC_FATURA { get; set; }
        public virtual ICollection<TEC_FATURA> TEC_FATURA1 { get; set; }
        public virtual ICollection<TEC_FATURA> TEC_FATURA2 { get; set; }
        public virtual ICollection<TEC_FATURA> TEC_FATURA3 { get; set; }
        public virtual ICollection<TEC_FATURA> TEC_FATURA4 { get; set; }
        public virtual ICollection<TEC_ITEM_PEDIDO> TEC_ITEM_PEDIDO { get; set; }
        public virtual ICollection<TEC_PAGAMENTO> TEC_PAGAMENTO { get; set; }
        public virtual ICollection<TEC_PAGAMENTO> TEC_PAGAMENTO1 { get; set; }
        public virtual ICollection<TEC_PAGAMENTO> TEC_PAGAMENTO2 { get; set; }
        public virtual ICollection<TEC_PAGAMENTO> TEC_PAGAMENTO3 { get; set; }
        public virtual ICollection<TEC_PAGAMENTO> TEC_PAGAMENTO4 { get; set; }
    }
}
