//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techshop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEC_USUARIO
    {
        public int COD_USUARIO { get; set; }
        public string DSC_USUARIO { get; set; }
        public string DSC_EMAIL { get; set; }
        public string DSC_LOGIN { get; set; }
        public string DSC_SENHA { get; set; }
        public int COD_EMPRESA { get; set; }
        public System.DateTime DTA_CADASTRO { get; set; }
        public int COD_PERFIL { get; set; }
        public System.DateTime DTA_EXPIRACAO { get; set; }
        public int IND_ATIVO { get; set; }
    }
}
