//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Techshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEC_PERFIL
    {
        public int COD_PERFIL { get; set; }
        public string DSC_PERFIL { get; set; }
    }
}
