//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protheus.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC5010
    {
        public string C5_FILIAL { get; set; }
        public string C5_NUM { get; set; }
        public string C5_TIPO { get; set; }
        public string C5_CLIENTE { get; set; }
        public string C5_LOJACLI { get; set; }
        public string C5_LOJAENT { get; set; }
        public string C5_TIPOCLI { get; set; }
        public string C5_CLIENT { get; set; }
        public string C5_TPFRETE { get; set; }
        public string C5_TRANSP { get; set; }
        public string C5_TABELA { get; set; }
        public string C5_CONDPAG { get; set; }
        public string C5_FORPAG { get; set; }
        public string C5_VEND1 { get; set; }
        public string C5_VEND2 { get; set; }
        public string C5_EMISSAO { get; set; }
        public double C5_FRETE { get; set; }
        public double C5_COMIS1 { get; set; }
        public double C5_COMIS2 { get; set; }
        public string C5_VEND3 { get; set; }
        public double C5_COMIS3 { get; set; }
        public string C5_VEND4 { get; set; }
        public double C5_COMIS4 { get; set; }
        public string C5_VEND5 { get; set; }
        public double C5_COMIS5 { get; set; }
        public double C5_DESC1 { get; set; }
        public double C5_DESC2 { get; set; }
        public double C5_DESC3 { get; set; }
        public double C5_DESC4 { get; set; }
        public string C5_BANCO { get; set; }
        public double C5_DESCFI { get; set; }
        public string C5_COTACAO { get; set; }
        public double C5_SEGURO { get; set; }
        public double C5_PESOL { get; set; }
        public double C5_PBRUTO { get; set; }
        public double C5_REIMP { get; set; }
        public string C5_REDESP { get; set; }
        public double C5_VOLUME1 { get; set; }
        public double C5_VOLUME2 { get; set; }
        public double C5_DESPESA { get; set; }
        public double C5_FRETAUT { get; set; }
        public string C5_REAJUST { get; set; }
        public double C5_MOEDA { get; set; }
        public double C5_VOLUME3 { get; set; }
        public double C5_VOLUME4 { get; set; }
        public string C5_ESPECI1 { get; set; }
        public string C5_ESPECI2 { get; set; }
        public string C5_ESPECI3 { get; set; }
        public string C5_ESPECI4 { get; set; }
        public double C5_ACRSFIN { get; set; }
        public string C5_MENNOTA { get; set; }
        public string C5_MENPAD { get; set; }
        public string C5_KITREP { get; set; }
        public string C5_TIPLIB { get; set; }
        public double C5_DESCONT { get; set; }
        public string C5_PEDEXP { get; set; }
        public string C5_TPCARGA { get; set; }
        public string C5_DTLANC { get; set; }
        public string C5_INCISS { get; set; }
        public string C5_LIBEROK { get; set; }
        public string C5_OK { get; set; }
        public string C5_NOTA { get; set; }
        public string C5_SERIE { get; set; }
        public double C5_PDESCAB { get; set; }
        public string C5_OS { get; set; }
        public string C5_BLQ { get; set; }
        public string C5_FORNISS { get; set; }
        public string C5_CONTRA { get; set; }
        public double C5_TXMOEDA { get; set; }
        public double C5_VLR_FRT { get; set; }
        public string C5_MDCONTR { get; set; }
        public string C5_MDNUMED { get; set; }
        public string C5_GERAWMS { get; set; }
        public string C5_MDPLANI { get; set; }
        public string C5_SOLFRE { get; set; }
        public string C5_FECENT { get; set; }
        public string C5_SOLOPC { get; set; }
        public string C5_SUGENT { get; set; }
        public string C5_CODED { get; set; }
        public string C5_NUMPR { get; set; }
        public string C5_RECISS { get; set; }
        public string C5_RECFAUT { get; set; }
        public string C5_MUNPRES { get; set; }
        public string C5_VEICULO { get; set; }
        public string C5_DESCMUN { get; set; }
        public string C5_PREPEMB { get; set; }
        public string C5_ORCRES { get; set; }
        public string C5_OBRA { get; set; }
        public double C5_PARC1 { get; set; }
        public string C5_DATA1 { get; set; }
        public double C5_PARC2 { get; set; }
        public string C5_DATA2 { get; set; }
        public string C5_SERSUBS { get; set; }
        public string C5_NFSUBST { get; set; }
        public double C5_PARC3 { get; set; }
        public string C5_DATA3 { get; set; }
        public double C5_PARC4 { get; set; }
        public string C5_DATA4 { get; set; }
        public double C5_PARC5 { get; set; }
        public string C5_DATA5 { get; set; }
        public double C5_PARC6 { get; set; }
        public string C5_DATA6 { get; set; }
        public double C5_PARC7 { get; set; }
        public string C5_DATA7 { get; set; }
        public double C5_PARC8 { get; set; }
        public string C5_DATA8 { get; set; }
        public double C5_PARC9 { get; set; }
        public string C5_DATA9 { get; set; }
        public double C5_PARCA { get; set; }
        public string C5_DATAA { get; set; }
        public string C5_BLOCLI { get; set; }
        public string C5_BLOQCS { get; set; }
        public string C5_FRCOMBI { get; set; }
        public string C5_MONTAGE { get; set; }
        public string C5_STMONT { get; set; }
        public double C5_VLDSC { get; set; }
        public string C5_CODRVD { get; set; }
        public string C5_LOJARVD { get; set; }
        public double C5_TXACRES { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public int R_E_C_N_O_ { get; set; }
        public int R_E_C_D_E_L_ { get; set; }
        public double C5_DSCTAB { get; set; }
        public string C5_OBSPED { get; set; }
        public string C5_LIBEXP { get; set; }
        public string C5_STREG { get; set; }
        public double C5_PARCB { get; set; }
        public string C5_DATAB { get; set; }
        public double C5_PARCC { get; set; }
        public string C5_DATAC { get; set; }
        public string C5_USERLGI { get; set; }
        public string C5_USERLGA { get; set; }
        public string C5_USRLIB { get; set; }
        public string C5_DTLIB { get; set; }
        public string C5_HRLIB { get; set; }
        public string C5_ESTPRES { get; set; }
        public string C5_LIBV { get; set; }
        public string C5_USLIBV { get; set; }
        public string C5_NTEMPEN { get; set; }
        public string C5_TIPOBRA { get; set; }
        public string C5_INDPRES { get; set; }
        public string C5_ZNUMENT { get; set; }
        public string C5_NUMENT { get; set; }
        public string C5_ORIGEM { get; set; }
        public string C5_DTTXREF { get; set; }
        public double C5_TXREF { get; set; }
        public double C5_MOEDTIT { get; set; }
        public string C5_NATUREZ { get; set; }
        public string C5_ECSEDEX { get; set; }
        public string C5_ECPRESN { get; set; }
        public string C5_ECVINCU { get; set; }
        public string C5_CLIINT { get; set; }
        public string C5_CGCINT { get; set; }
        public string C5_IMINT { get; set; }
        public string C5_ZRETREM { get; set; }
        public double C5_PARCD { get; set; }
        public string C5_DATAD { get; set; }
        public double C5_PARCE { get; set; }
        public string C5_DATAE { get; set; }
        public string C5_ZTXRVD { get; set; }
        public string C5_DTESERV { get; set; }
        public string C5_CLIRET { get; set; }
        public string C5_LOJARET { get; set; }
    }
}
