//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protheus.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC6010
    {
        public string C6_FILIAL { get; set; }
        public string C6_ITEM { get; set; }
        public string C6_PRODUTO { get; set; }
        public string C6_LOCAL { get; set; }
        public string C6_DESCRI { get; set; }
        public string C6_UM { get; set; }
        public double C6_QTDVEN { get; set; }
        public double C6_PRCVEN { get; set; }
        public double C6_VALOR { get; set; }
        public string C6_SEGUM { get; set; }
        public double C6_QTDLIB { get; set; }
        public double C6_QTDLIB2 { get; set; }
        public string C6_TES { get; set; }
        public double C6_UNSVEN { get; set; }
        public double C6_QTDENT2 { get; set; }
        public double C6_QTDENT { get; set; }
        public string C6_CF { get; set; }
        public string C6_CLI { get; set; }
        public double C6_DESCONT { get; set; }
        public string C6_ENTREG { get; set; }
        public string C6_LA { get; set; }
        public double C6_VALDESC { get; set; }
        public string C6_LOJA { get; set; }
        public string C6_NOTA { get; set; }
        public string C6_DATFAT { get; set; }
        public string C6_SERIE { get; set; }
        public string C6_NUM { get; set; }
        public double C6_COMIS1 { get; set; }
        public double C6_COMIS2 { get; set; }
        public double C6_COMIS3 { get; set; }
        public double C6_COMIS4 { get; set; }
        public double C6_COMIS5 { get; set; }
        public string C6_PEDCLI { get; set; }
        public double C6_PRUNIT { get; set; }
        public string C6_BLOQUEI { get; set; }
        public string C6_RESERVA { get; set; }
        public string C6_OP { get; set; }
        public string C6_OK { get; set; }
        public string C6_NFORI { get; set; }
        public string C6_SERIORI { get; set; }
        public string C6_ITEMORI { get; set; }
        public double C6_IPIDEV { get; set; }
        public string C6_IDENTB6 { get; set; }
        public string C6_BLQ { get; set; }
        public double C6_PICMRET { get; set; }
        public string C6_CODISS { get; set; }
        public string C6_GRADE { get; set; }
        public string C6_ITEMGRD { get; set; }
        public string C6_LOTECTL { get; set; }
        public string C6_NUMLOTE { get; set; }
        public string C6_DTVALID { get; set; }
        public string C6_NUMORC { get; set; }
        public string C6_CHASSI { get; set; }
        public string C6_OPC { get; set; }
        public string C6_LOCALIZ { get; set; }
        public string C6_NUMSERI { get; set; }
        public string C6_NUMOP { get; set; }
        public string C6_ITEMOP { get; set; }
        public string C6_CLASFIS { get; set; }
        public double C6_QTDRESE { get; set; }
        public string C6_CONTRAT { get; set; }
        public string C6_NUMOS { get; set; }
        public string C6_NUMOSFA { get; set; }
        public string C6_CODFAB { get; set; }
        public string C6_LOJAFA { get; set; }
        public string C6_ITEMCON { get; set; }
        public string C6_TPOP { get; set; }
        public string C6_REVISAO { get; set; }
        public string C6_SERVIC { get; set; }
        public string C6_ENDPAD { get; set; }
        public string C6_TPESTR { get; set; }
        public string C6_CONTRT { get; set; }
        public string C6_TPCONTR { get; set; }
        public string C6_ITCONTR { get; set; }
        public string C6_GEROUPV { get; set; }
        public string C6_PROJPMS { get; set; }
        public string C6_EDTPMS { get; set; }
        public string C6_TASKPMS { get; set; }
        public string C6_TRT { get; set; }
        public double C6_QTDEMP { get; set; }
        public double C6_QTDEMP2 { get; set; }
        public string C6_PROJET { get; set; }
        public string C6_ITPROJ { get; set; }
        public double C6_POTENCI { get; set; }
        public string C6_LICITA { get; set; }
        public string C6_REGWMS { get; set; }
        public byte[] C6_MOPC { get; set; }
        public string C6_NUMCP { get; set; }
        public string C6_NUMSC { get; set; }
        public string C6_ITEMSC { get; set; }
        public string C6_SUGENTR { get; set; }
        public string C6_ITEMED { get; set; }
        public double C6_ABSCINS { get; set; }
        public double C6_ABATISS { get; set; }
        public double C6_ABATMAT { get; set; }
        public double C6_FUNRURA { get; set; }
        public double C6_FETAB { get; set; }
        public string C6_CODROM { get; set; }
        public string C6_PROGRAM { get; set; }
        public string C6_TURNO { get; set; }
        public string C6_LOJDED { get; set; }
        public string C6_CODLAN { get; set; }
        public string C6_FORDED { get; set; }
        public string C6_ITPC { get; set; }
        public string C6_PVCOMOP { get; set; }
        public string C6_VDMOST { get; set; }
        public string C6_FILPED { get; set; }
        public string C6_PEDCOM { get; set; }
        public byte[] C6_VDOBS { get; set; }
        public string C6_TPDEDUZ { get; set; }
        public string C6_MOTDED { get; set; }
        public double C6_VLDED { get; set; }
        public double C6_VLNFD { get; set; }
        public string C6_RATEIO { get; set; }
        public string C6_SERDED { get; set; }
        public double C6_PCDED { get; set; }
        public string C6_NFDED { get; set; }
        public string C6_ITLPRE { get; set; }
        public string C6_D1SERIE { get; set; }
        public string C6_D1DOC { get; set; }
        public string C6_CODLPRE { get; set; }
        public string C6_D1ITEM { get; set; }
        public double C6_ABATINS { get; set; }
        public double C6_VALST { get; set; }
        public double C6_PCREAL { get; set; }
        public string D_E_L_E_T_ { get; set; }
        public int R_E_C_N_O_ { get; set; }
        public int R_E_C_D_E_L_ { get; set; }
        public string C6_USERLGI { get; set; }
        public string C6_USERLGA { get; set; }
        public string C6_TNATREC { get; set; }
        public string C6_CNATREC { get; set; }
        public string C6_GRPNATR { get; set; }
        public string C6_DTFIMNT { get; set; }
        public string C6_MONTAGE { get; set; }
        public double C6_SVCUST { get; set; }
        public string C6_ID { get; set; }
        public double C6_VLIMPOR { get; set; }
        public double C6_BASVEIC { get; set; }
        public string C6_FCICOD { get; set; }
        public string C6_ITEMPC { get; set; }
        public string C6_NUMPCOM { get; set; }
        public string C6_HORENT { get; set; }
        public string C6_PMSID { get; set; }
        public string C6_PEDVINC { get; set; }
        public string C6_REVPROD { get; set; }
        public string C6_CODINF { get; set; }
        public string C6_PRODFIN { get; set; }
    }
}
